#pragma once
#include <cstdint>

/*
 * Rocket League Season 20 (v2.56) 09/24/2025 07:09PM - SDK Offsets
 * Generated by CodeRedGenerator v1.1.5
 * 09/24/2025 07:09PM
 */

namespace Offsets {

// ========================= GLOBAL ADDRESSES =========================
constexpr uintptr_t BASE_ADDRESS = 0x7FF7BB280000;
constexpr uintptr_t GNAMES_OFFSET = 0x23C7800;
constexpr uintptr_t GOBJECTS_OFFSET = 0x23C7848;

// ========================= PROCESS EVENT =========================
constexpr int32_t PROCESS_EVENT_INDEX = 67;

// ========================= FNameEntry =========================
namespace FNameEntry {
	constexpr uintptr_t FLAGS = 0x0; // 0
	constexpr uintptr_t INDEX = 0x8; // 8
	constexpr uintptr_t NAME[0X400] = 0x18; // 24
	constexpr size_t CLASS_SIZE = 0x818; // 2072
}

// ========================= UObject =========================
namespace UObject {
	constexpr uintptr_t VFTABLEOBJECT = 0x0; // 0
	constexpr uintptr_t OBJECTINTERNALINTEGER = 0x38; // 56
	constexpr uintptr_t OUTER = 0x40; // 64
	constexpr uintptr_t NAME = 0x48; // 72
	constexpr uintptr_t CLASS = 0x50; // 80
	constexpr size_t CLASS_SIZE = 0x60; // 96
}

// ========================= UField =========================
namespace UField {
	constexpr uintptr_t NEXT = 0x60; // 96
	constexpr size_t CLASS_SIZE = 0x70; // 112
}

// ========================= UEnum =========================
namespace UEnum {
	constexpr uintptr_t NAMES = 0x70; // 112
	constexpr size_t CLASS_SIZE = 0x80; // 128
}

// ========================= UConst =========================
namespace UConst {
	constexpr uintptr_t VALUE = 0x70; // 112
	constexpr size_t CLASS_SIZE = 0x80; // 128
}

// ========================= UProperty =========================
namespace UProperty {
	constexpr uintptr_t ARRAYDIM = 0x70; // 112
	constexpr uintptr_t ELEMENTSIZE = 0x74; // 116
	constexpr uintptr_t PROPERTYFLAGS = 0x78; // 120
	constexpr uintptr_t OFFSET = 0x98; // 152
	constexpr size_t CLASS_SIZE = 0xC8; // 200
}

// ========================= UStruct =========================
namespace UStruct {
	constexpr uintptr_t SUPERFIELD = 0x80; // 128
	constexpr uintptr_t CHILDREN = 0x88; // 136
	constexpr uintptr_t PROPERTYSIZE = 0x90; // 144
	constexpr uintptr_t MINALIGNMENT = 0xB0; // 176
	constexpr size_t CLASS_SIZE = 0x130; // 304
}

// ========================= UFunction =========================
namespace UFunction {
	constexpr uintptr_t FUNCTIONFLAGS = 0x130; // 304
	constexpr uintptr_t INATIVE = 0x138; // 312
	constexpr size_t CLASS_SIZE = 0x160; // 352
}

// ========================= UStructProperty =========================
namespace UStructProperty {
	constexpr uintptr_t STRUCT = 0xC8; // 200
	constexpr size_t CLASS_SIZE = 0xD0; // 208
}

// ========================= UObjectProperty =========================
namespace UObjectProperty {
	constexpr uintptr_t PROPERTYCLASS = 0xC8; // 200
	constexpr size_t CLASS_SIZE = 0xD8; // 216
}

// ========================= UClassProperty =========================
namespace UClassProperty {
	constexpr uintptr_t METACLASS = 0xD8; // 216
	constexpr size_t CLASS_SIZE = 0xE0; // 224
}

// ========================= UMapProperty =========================
namespace UMapProperty {
	constexpr uintptr_t KEY = 0xC8; // 200
	constexpr uintptr_t VALUE = 0xD0; // 208
	constexpr size_t CLASS_SIZE = 0xD8; // 216
}

// ========================= UInterfaceProperty =========================
namespace UInterfaceProperty {
	constexpr uintptr_t INTERFACECLASS = 0xC8; // 200
	constexpr size_t CLASS_SIZE = 0xD8; // 216
}

// ========================= UByteProperty =========================
namespace UByteProperty {
	constexpr uintptr_t ENUM = 0xC8; // 200
	constexpr size_t CLASS_SIZE = 0xD0; // 208
}

// ========================= UBoolProperty =========================
namespace UBoolProperty {
	constexpr uintptr_t BITMASK = 0xC8; // 200
	constexpr size_t CLASS_SIZE = 0xD0; // 208
}

// ========================= UArrayProperty =========================
namespace UArrayProperty {
	constexpr uintptr_t INNER = 0xC8; // 200
	constexpr size_t CLASS_SIZE = 0xD0; // 208
}

// ========================= ENGINE SPECIFIC =========================
namespace Engine {
	// Add any engine-specific offsets here
	// These can be manually updated for specific game versions
}

// ========================= UTILITY FUNCTIONS =========================
inline uintptr_t GetGNamesAddress() { return BASE_ADDRESS + GNAMES_OFFSET; }
inline uintptr_t GetGObjectsAddress() { return BASE_ADDRESS + GOBJECTS_OFFSET; }

} // namespace Offsets
