#pragma once
// Hybrid SDK bridge for ProcessInternal access
// Auto-generated by SDK Merge Tool

#include "Core_classes.hpp"

inline void* GetProcessInternalPtr(UFunction* fn) {
    if (!fn) return nullptr;
    return *(void**)((uintptr_t)fn + 0x98); // fallback offset if Func missing
}

// Legacy compatibility macros
#define ProcessInternal(fn, params, result) GetProcessInternalPtr(fn)
